# <font color='brown'>NumPy 百题大冲关</font>

## 实验介绍

![numpylogo.png](attachment/numpylogo.png)

NumPy 是 Python 语言的一个扩充程序库。支持大量高维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。机器学习涉及到大量对数组的变换和运算，NumPy 就成了必不可少的工具之一。

**NumPy 百题大冲关**分为基础篇和进阶篇，每部分各有 50 道练习题。基础部分的练习题在于熟悉 NumPy 常用方法的使用，而进阶部分则侧重于 NumPy 方法的组合应用。

如果你在学习课程之前已经有 NumPy 使用基础，那么可以对照着单元格复习一遍。如果你对 NumPy 并不熟练，就一定要<font color='brown'>亲自动手</font>在每个示例单元格下方的空白单元格中练习。

### 实验知识点

本次实验涉及的知识点主要有：
- 创建数组
- 数组运算
- 数学函数
- 数组切片和索引
- 数组形状操作
- 数组排序
- 数组统计

### 实验环境

- Python 3.6
- NumPy: 1.14.3

### 目录索引

- <a href="#1">1. 基础部分</a>
- <a href="#2">2. 进阶部分</a>
- <a href="#3">3. 实验总结</a>

## <a id = "1">1. 基础部分</a>

### 导入 NumPy

#### 1. 导入 NumPy
练习 NumPy 之前，首先需要导入 NumPy 模块，并约定简称为 `np`。

In [1]:
import numpy as np

#### 2. 查看 NumPy 版本信息

In [2]:
print(np.__version__)

1.14.3


### 创建数组

NumPy 的主要对象是多维数组 Ndarray。在 NumPy 中维度（dimensions）叫做轴（axes），轴的个数叫做秩（rank）。

例如，下方数组是一个秩为 1 的数组，因为它只有一个轴，而轴的长度为 3。
```
[1, 2, 3]
``` 

又例如，下方数组的秩为 2。第一个维度长度为 2,第二个维度长度为 3。

```
[[1., 2., 3.],
 [4., 5., 6.]]
```

#### 3. 通过列表创建一维数组

注意：`numpy.array` 和 Python 标准库 `array.array` 并不相同，前者更为强大，这也就是我们学习 Numpy 的重要原因之一。

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

#### 4. 通过列表创建二维数组

In [4]:
np.array([(1, 2, 3), (4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

#### 5. 创建全为 0 的二维数组

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 6. 创建全为 1 的三维数组

In [6]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

注意：务必想清楚上面 4 个数组的维度关系

#### 7. 创建一维等差数组

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

#### 8. 创建二维等差数组

In [8]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

#### 9. 创建单位矩阵（二维数组）

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 10. 创建等间隔一维数组

In [10]:
np.linspace(1, 10, num=6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

#### 11. 创建二维随机数组

In [11]:
np.random.rand(2,3)

array([[0.71642519, 0.95502829, 0.74831079],
       [0.82696317, 0.72818278, 0.13246486]])

#### 12. 创建二维随机整数数组（数值小于 5）

In [12]:
np.random.randint(5, size=(2,3))

array([[2, 3, 3],
       [2, 0, 1]])

#### 13. 依据自定义函数创建数组

In [13]:
np.fromfunction(lambda i, j: i + j, (3, 3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

### 数组运算

#### 生成一维示例数组

In [14]:
a = np.array([10,20,30,40,50])
b = np.arange(1,6)
a,b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

#### 14. 一维数组加法运算

In [15]:
a + b

array([11, 22, 33, 44, 55])

#### 15. 一维数组减法运算

In [16]:
a - b

array([ 9, 18, 27, 36, 45])

#### 16. 一维数组乘法运算m

In [17]:
a * b

array([ 10,  40,  90, 160, 250])

#### 17. 一维数组除法运算

In [18]:
a / b

array([10, 10, 10, 10, 10])

#### 生成二维示例数组（可以看作矩阵）

In [19]:
A = np.array([[1,2],
           [3,4]])
B = np.array([[5,6],
           [7,8]])
A, B

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

#### 18. 矩阵加法运算

In [20]:
A + B

array([[ 6,  8],
       [10, 12]])

#### 19. 矩阵减法运算

In [21]:
A - B

array([[-4, -4],
       [-4, -4]])

#### 20. 矩阵元素间乘法运算

In [22]:
A * B

array([[ 5, 12],
       [21, 32]])

#### 21. 矩阵乘法运算（注意与上题的区别）

In [23]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

<div style="color: #999;font-size: 12px;font-style: italic;">*如果不了解矩阵乘法运算，<a href="https://baike.baidu.com/item/%E7%9F%A9%E9%98%B5%E4%B9%98%E6%B3%95">点击此链接</a>学习。</div>

In [24]:
# 如果使用 np.mat 将二维数组准确定义为矩阵，就可以直接使用 * 完成矩阵乘法计算
np.mat(A) * np.mat(B)

matrix([[19, 22],
        [43, 50]])

#### 22. 数乘矩阵

In [25]:
2 * A

array([[2, 4],
       [6, 8]])

#### 23. 矩阵的转置

In [26]:
A.T

array([[1, 3],
       [2, 4]])

#### 24. 矩阵求逆

In [27]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 数学函数

#### 25. 三角函数

In [28]:
print(a)

np.sin(a)

[10 20 30 40 50]


array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

#### 26. 以自然对数函数为底数的指数函数

In [29]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

#### 27. 数组的方根的运算（开平方）

In [30]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

#### 28. 数组的方根的运算（立方）

In [31]:
np.power(a, 3)

array([  1000,   8000,  27000,  64000, 125000])

### 数组切片和索引

#### 29. 一维数组索引

In [32]:
a = np.array([1, 2, 3, 4, 5])
a[0], a[-1]

(1, 5)

#### 30. 一维数组切片

In [33]:
a[0:2], a[:-1]

(array([1, 2]), array([1, 2, 3, 4]))

#### 31. 二维数组索引

In [34]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a[0], a[-1]

(array([1, 2, 3]), array([7, 8, 9]))

#### 32. 二维数组切片（取第 2 列）

In [35]:
print(a)

a[:, 1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 5, 8])

#### 33. 二维数组切片（取第 2，3 行）

In [36]:
a[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])

### 数组形状操作

#### 生成一维示例数组

In [37]:
a = np.random.random((3, 2))
a

array([[0.34726699, 0.60472646],
       [0.23426322, 0.74807912],
       [0.57072295, 0.48753785]])

#### 34. 查看数组形状

In [38]:
a.shape

(3, 2)

#### 35. 更改数组形状（不改变原始数组）

In [39]:
# reshape 并不改变原始数组
a.reshape(2, 3)

array([[0.34726699, 0.60472646, 0.23426322],
       [0.74807912, 0.57072295, 0.48753785]])

In [40]:
a

array([[0.34726699, 0.60472646],
       [0.23426322, 0.74807912],
       [0.57072295, 0.48753785]])

#### 36. 更改数组形状（改变原始数组）

In [41]:
a.resize(2, 3)

In [42]:
a

array([[0.34726699, 0.60472646, 0.23426322],
       [0.74807912, 0.57072295, 0.48753785]])

#### 37. 展平数组

In [43]:
a.ravel()

array([0.34726699, 0.60472646, 0.23426322, 0.74807912, 0.57072295,
       0.48753785])

#### 38. 垂直拼合数组

In [44]:
# 生成示例数组
a = np.random.randint(10, size=(3, 3))
b = np.random.randint(10, size=(3, 3))

a, b

(array([[9, 7, 2],
        [8, 4, 1],
        [4, 1, 4]]), array([[1, 8, 3],
        [8, 5, 8],
        [2, 7, 5]]))

In [45]:
np.vstack((a, b))

array([[9, 7, 2],
       [8, 4, 1],
       [4, 1, 4],
       [1, 8, 3],
       [8, 5, 8],
       [2, 7, 5]])

#### 39. 水平拼合数组

In [46]:
np.hstack((a, b))

array([[9, 7, 2, 1, 8, 3],
       [8, 4, 1, 8, 5, 8],
       [4, 1, 4, 2, 7, 5]])

#### 40. 沿横轴分割数组

In [47]:
np.hsplit(a, 3)

[array([[9],
        [8],
        [4]]), array([[7],
        [4],
        [1]]), array([[2],
        [1],
        [4]])]

#### 41. 沿纵轴分割数组

In [48]:
np.vsplit(a, 3)

[array([[9, 7, 2]]), array([[8, 4, 1]]), array([[4, 1, 4]])]

### 数组排序

In [49]:
# 生成示例数组
a = np.array(([1,4,3],[6,2,9],[4,7,2]))
a

array([[1, 4, 3],
       [6, 2, 9],
       [4, 7, 2]])

#### 42. 返回每列最大值

In [50]:
np.max(a, axis=0)

array([6, 7, 9])

#### 43. 返回每行最小值

In [51]:
np.min(a, axis=1)

array([1, 2, 2])

#### 44. 返回每列最大值索引

In [52]:
np.argmax(a, axis=0)

array([1, 2, 1])

#### 45. 返回每行最小值索引

In [53]:
np.argmin(a, axis=1)

array([0, 1, 2])

### 数组统计

#### 46. 统计数组各列的中位数

In [54]:
# 继续使用上面的 a 数组
np.median(a, axis=0)

array([4., 4., 3.])

#### 47. 统计数组各行的算术平均值

In [55]:
np.mean(a, axis=1)

array([2.66666667, 5.66666667, 4.33333333])

#### 48. 统计数组各列的加权平均值

In [56]:
np.average(a, axis=0)

array([3.66666667, 4.33333333, 4.66666667])

#### 49. 统计数组各行的方差

In [57]:
np.var(a, axis=1)

array([1.55555556, 8.22222222, 4.22222222])

#### 50. 统计数组各列的标准偏差

In [58]:
np.std(a, axis=0)

array([2.05480467, 2.05480467, 3.09120617])

---
##  <a id = "2">2. 进阶部分[选学]</a>

#### 51. 创建一个 5x5 的二维数组，其中边界值为1，其余值为0

In [59]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 52. 使用数字 0 将一个全为 1 的 5x5 二维数组包围

In [60]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 53. 创建一个 5x5 的二维数组，并设置值 1, 2, 3, 4 落在其对角线下方

In [61]:
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 54. 创建一个 10x10 的二维数组，并使得 1 和 0 沿对角线间隔放置

In [62]:
Z = np.zeros((10,10),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

#### 55. 创建一个 0-10 的一维数组，并将 (1, 9] 之间的数全部反转成负数

In [63]:
Z = np.arange(11)
Z[(1 < Z) & (Z <= 9)] *= -1
Z

array([ 0,  1, -2, -3, -4, -5, -6, -7, -8, -9, 10])

#### 56. 找出两个一维数组中相同的元素

In [64]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print("Z1:", Z1)
print("Z2:", Z2)
np.intersect1d(Z1,Z2)

('Z1:', array([3, 7, 6, 2, 6, 5, 1, 6, 9, 9]))
('Z2:', array([7, 3, 1, 4, 5, 6, 8, 7, 5, 8]))


array([1, 3, 5, 6, 7])

#### 57. 使用 NumPy 打印昨天、今天、明天的日期

In [65]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("yesterday: ", yesterday)
print("today: ", today)
print("tomorrow: ", tomorrow)

('yesterday: ', numpy.datetime64('2018-06-03'))
('today: ', numpy.datetime64('2018-06-04'))
('tomorrow: ', numpy.datetime64('2018-06-05'))


#### 58. 使用五种不同的方法去提取一个随机数组的整数部分

In [66]:
Z = np.random.uniform(0,10,10)
print(u"原始值: ", Z)

print(u"方法 1: ", Z - Z%1)
print(u"方法 2: ", np.floor(Z))
print(u"方法 3: ", np.ceil(Z)-1)
print(u"方法 4: ", Z.astype(int))
print(u"方法 5: ", np.trunc(Z))

(u'\u539f\u59cb\u503c: ', array([2.20739194, 7.8095524 , 0.98133102, 0.27478194, 4.98516434,
       2.29422454, 4.99640474, 1.30793223, 5.86245449, 2.89489596]))
(u'\u65b9\u6cd5 1: ', array([2., 7., 0., 0., 4., 2., 4., 1., 5., 2.]))
(u'\u65b9\u6cd5 2: ', array([2., 7., 0., 0., 4., 2., 4., 1., 5., 2.]))
(u'\u65b9\u6cd5 3: ', array([2., 7., 0., 0., 4., 2., 4., 1., 5., 2.]))
(u'\u65b9\u6cd5 4: ', array([2, 7, 0, 0, 4, 2, 4, 1, 5, 2]))
(u'\u65b9\u6cd5 5: ', array([2., 7., 0., 0., 4., 2., 4., 1., 5., 2.]))


#### 59. 创建一个 5x5 的矩阵，其中每行的数值范围从 1 到 5

In [67]:
Z = np.zeros((5,5))
Z += np.arange(1,6)

Z

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

#### 60. 创建一个长度为 5 的等间隔一维数组，其值域范围从 0 到 1，但是不包括 0 和 1

In [68]:
Z = np.linspace(0,1,6,endpoint=False)[1:]

Z

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

#### 61. 创建一个长度为10的随机一维数组，并将其按升序排序

In [69]:
Z = np.random.random(10)
Z.sort()
Z

array([0.02668681, 0.11738198, 0.19099965, 0.21369872, 0.24955787,
       0.26235991, 0.36045461, 0.43925993, 0.45220163, 0.71431813])

#### 62. 创建一个 3x3 的二维数组，并将列按升序排序

In [70]:
Z = np.array([[7,4,3],[3,1,2],[4,2,6]])
print(u"原始数组: \n", Z)

Z.sort(axis=0)
Z

(u'\u539f\u59cb\u6570\u7ec4: \n', array([[7, 4, 3],
       [3, 1, 2],
       [4, 2, 6]]))


array([[3, 1, 2],
       [4, 2, 3],
       [7, 4, 6]])

#### 63. 创建一个长度为 5 的一维数组，并将其中最大值替换成 0

In [71]:
Z = np.random.random(5)
print(u"原数组: ",Z)
Z[Z.argmax()] = 0
Z

(u'\u539f\u6570\u7ec4: ', array([0.72081809, 0.91579644, 0.47111013, 0.87893815, 0.43135868]))


array([0.72081809, 0.        , 0.47111013, 0.87893815, 0.43135868])

#### 64. 打印每个 NumPy 标量类型的最小值和最大值

In [72]:
for dtype in [np.int8, np.int32, np.int64]:
   print("The minimum value of {}: ".format(dtype), np.iinfo(dtype).min)
   print("The maximum value of {}: ".format(dtype),np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print("The minimum value of {}: ".format(dtype),np.finfo(dtype).min)
   print("The maximum value of {}: ".format(dtype),np.finfo(dtype).max)

("The minimum value of <type 'numpy.int8'>: ", -128)
("The maximum value of <type 'numpy.int8'>: ", 127)
("The minimum value of <type 'numpy.int32'>: ", -2147483648)
("The maximum value of <type 'numpy.int32'>: ", 2147483647)
("The minimum value of <type 'numpy.int64'>: ", -9223372036854775808)
("The maximum value of <type 'numpy.int64'>: ", 9223372036854775807)
("The minimum value of <type 'numpy.float32'>: ", -3.4028235e+38)
("The maximum value of <type 'numpy.float32'>: ", 3.4028235e+38)
("The minimum value of <type 'numpy.float64'>: ", -1.7976931348623157e+308)
("The maximum value of <type 'numpy.float64'>: ", 1.7976931348623157e+308)


#### 65. 将 `float32` 转换为整型

In [73]:
Z = np.arange(10, dtype=np.float32)
print(Z)

Z = Z.astype(np.int32, copy=False)
Z

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 66. 将随机二维数组按照第 3 列从上到下进行升序排列

In [74]:
Z = np.random.randint(0,10,(5,5))
print(u"排序前：\n",Z)

Z[Z[:,2].argsort()]

(u'\u6392\u5e8f\u524d\uff1a\n', array([[5, 6, 3, 7, 0],
       [9, 3, 6, 6, 2],
       [7, 4, 1, 5, 9],
       [0, 4, 8, 6, 7],
       [7, 9, 7, 4, 7]]))


array([[7, 4, 1, 5, 9],
       [5, 6, 3, 7, 0],
       [9, 3, 6, 6, 2],
       [7, 9, 7, 4, 7],
       [0, 4, 8, 6, 7]])

#### 67. 从随机一维数组中找出距离给定数值（0.5）最近的数

In [75]:
Z = np.random.uniform(0,1,20)
print(u"随机数组: \n", Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]

m

(u'\u968f\u673a\u6570\u7ec4: \n', array([0.94585628, 0.82585506, 0.79538169, 0.83088156, 0.40668051,
       0.68930858, 0.31846356, 0.4646269 , 0.28503716, 0.90658039,
       0.04138978, 0.79755238, 0.59826264, 0.52006891, 0.29279219,
       0.49090866, 0.1025735 , 0.74222986, 0.70942997, 0.5583902 ]))


0.49090866071073225

#### 68. 将二维数组的前两行进行顺序交换

In [76]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 69. 找出随机一维数组中出现频率最高的值

In [77]:
Z = np.random.randint(0,10,50)
print(u"随机一维数组:", Z)
np.bincount(Z).argmax()

(u'\u968f\u673a\u4e00\u7ef4\u6570\u7ec4:', array([0, 7, 0, 1, 4, 1, 7, 3, 6, 6, 3, 8, 0, 3, 2, 2, 6, 3, 4, 7, 0, 3,
       2, 1, 7, 5, 9, 9, 8, 3, 7, 9, 5, 9, 2, 4, 7, 6, 7, 6, 3, 6, 3, 8,
       3, 1, 6, 1, 7, 3]))


3

#### 70. 找出给定一维数组中非 0 元素的位置索引

In [78]:
Z = np.nonzero([1,0,2,0,1,0,4,0])
Z

(array([0, 2, 4, 6]),)

#### 71. 对于给定的 5x5 二维数组，在其内部随机放置 p 个值为 1 的数

In [79]:
p = 3

Z = np.zeros((5,5))
np.put(Z, np.random.choice(range(5*5), p, replace=False),1)

Z

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

#### 72. 对于随机的 3x3 二维数组，减去数组每一行的平均值

In [80]:
X = np.random.rand(3, 3)
print(X)

Y = X - X.mean(axis=1, keepdims=True)
Y

[[1.13819801e-04 7.52516840e-01 1.97413250e-01]
 [6.65069448e-01 8.56677784e-02 4.35097856e-01]
 [8.44148919e-01 9.74653724e-01 4.44802849e-02]]


array([[-0.31656748,  0.43583554, -0.11926805],
       [ 0.26979109, -0.30961058,  0.03981949],
       [ 0.22305461,  0.35355941, -0.57661402]])

#### 73. 获得二维数组点积结果的对角线数组

In [81]:
A = np.random.uniform(0,1,(3,3))
B = np.random.uniform(0,1,(3,3))

print(np.dot(A, B))

# 较慢的方法
np.diag(np.dot(A, B))

[[0.92367894 1.26430925 0.9592138 ]
 [0.54042251 0.76082445 0.54420011]
 [0.78032126 0.84501865 0.69246705]]


array([0.92367894, 0.76082445, 0.69246705])

In [82]:
# 较快的方法
np.sum(A * B.T, axis=1)

array([0.92367894, 0.76082445, 0.69246705])

In [83]:
# 更快的方法
np.einsum("ij, ji->i", A, B)

array([0.92367894, 0.76082445, 0.69246705])

#### 74. 找到随机一维数组中前 p 个最大值

In [84]:
Z = np.random.randint(1,100,100)
print(Z)

p = 5

Z[np.argsort(Z)[-p:]]

[13 10 51  5 58 14 81 50 78 28 28  4 87  2 33 31 40  1 97 98 23 24 43 11
  8 14 55 32  5 56 95 84 77 61  1 95 10 29 89 41 95 79 92 53 13 82 89 82
 10 80 35 84 39 63 84 43 38 31 61 81 87 72  7 78 77 91 76 24  8 64 27 99
 20 58 75 62 94 92  1 82 49 22 53  5 96 86 98 12 91 34 35 60 10 38 33 34
  4 84 27 43]


array([96, 97, 98, 98, 99])

#### 75. 计算随机一维数组中每个元素的 4 次方数值

In [85]:
x = np.random.randint(2,5,5)
print(x)

np.power(x,4)

[4 2 2 3 4]


array([256,  16,  16,  81, 256])

#### 76. 对于二维随机数组中各元素，保留其 2 位小数

In [86]:
Z = np.random.random((5,5))
print(Z)

np.set_printoptions(precision=2)
Z

[[0.73853004 0.68594085 0.08813696 0.84113535 0.24398536]
 [0.62793005 0.91450649 0.54296314 0.08215956 0.37995048]
 [0.78813515 0.74243172 0.54573548 0.60712654 0.29188499]
 [0.79642899 0.54839392 0.35605893 0.94354142 0.33612983]
 [0.95102551 0.09249394 0.42850496 0.0223711  0.54833744]]


array([[0.74, 0.69, 0.09, 0.84, 0.24],
       [0.63, 0.91, 0.54, 0.08, 0.38],
       [0.79, 0.74, 0.55, 0.61, 0.29],
       [0.8 , 0.55, 0.36, 0.94, 0.34],
       [0.95, 0.09, 0.43, 0.02, 0.55]])

#### 77. 使用科学记数法输出 NumPy 数组

In [87]:
Z = np.random.random([5,5])
print(Z)

Z/1e3

[[0.81 0.58 0.04 0.59 0.95]
 [0.13 0.21 0.62 0.41 0.14]
 [0.95 0.49 0.19 0.56 0.79]
 [0.52 0.61 0.98 0.94 0.74]
 [0.48 0.14 0.95 0.09 0.53]]


array([[8.06e-04, 5.75e-04, 4.16e-05, 5.87e-04, 9.54e-04],
       [1.32e-04, 2.14e-04, 6.20e-04, 4.08e-04, 1.36e-04],
       [9.48e-04, 4.87e-04, 1.91e-04, 5.60e-04, 7.91e-04],
       [5.22e-04, 6.12e-04, 9.79e-04, 9.45e-04, 7.44e-04],
       [4.81e-04, 1.39e-04, 9.48e-04, 8.90e-05, 5.31e-04]])

#### 78. 使用 NumPy 找出百分位数（25%，50%，75%）

In [88]:
a = np.arange(15)
print(a)

np.percentile(a, q=[25, 50, 75])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 3.5,  7. , 10.5])

#### 79. 找出数组中缺失值的总数及所在位置

In [89]:
# 生成含缺失值的 2 维数组
Z = np.random.rand(10,10)
Z[np.random.randint(10, size=5), np.random.randint(10, size=5)] = np.nan
Z

array([[0.27,  nan, 0.32, 0.83, 0.48, 0.67, 0.62, 0.17, 0.21, 0.14],
       [0.95, 0.96, 0.99, 0.88, 0.89, 0.2 , 0.17, 0.66, 0.89, 0.07],
       [0.97,  nan, 0.43, 0.98, 0.27, 0.21, 0.74, 0.2 , 0.81, 0.99],
       [0.93, 0.27, 0.54, 0.14, 0.03, 0.38, 0.33, 0.94, 0.48, 0.75],
       [0.19,  nan, 0.87, 0.89, 0.58, 0.58, 0.09, 0.56, 0.92, 0.62],
       [0.9 , 0.43, 0.42, 0.86, 0.28, 0.26, 0.53, 0.01, 0.29, 0.53],
       [ nan, 0.27, 0.41, 0.81, 0.78, 0.83, 0.35, 0.76, 0.46, 0.69],
       [0.41, 0.22, 0.96, 0.12, 0.42, 0.82, 0.99, 0.74, 0.65, 0.58],
       [0.58, 0.19, 0.01, 0.62, 0.44, 0.72, 0.56, 0.12, 0.27, 0.83],
       [0.77, 0.05, 0.35,  nan, 0.97, 0.68, 0.15, 0.56, 0.98, 0.44]])

In [90]:
print("缺失值总数: \n", np.isnan(Z).sum())
print("缺失值索引: \n", np.where(np.isnan(Z)))

('\xe7\xbc\xba\xe5\xa4\xb1\xe5\x80\xbc\xe6\x80\xbb\xe6\x95\xb0: \n', 5)
('\xe7\xbc\xba\xe5\xa4\xb1\xe5\x80\xbc\xe7\xb4\xa2\xe5\xbc\x95: \n', (array([0, 2, 4, 6, 9]), array([1, 1, 1, 0, 3])))


#### 80. 从随机数组中删除包含缺失值的行

In [91]:
# 沿用 79 题中的含缺失值的 2 维数组

Z[np.sum(np.isnan(Z), axis=1) == 0]

array([[0.95, 0.96, 0.99, 0.88, 0.89, 0.2 , 0.17, 0.66, 0.89, 0.07],
       [0.93, 0.27, 0.54, 0.14, 0.03, 0.38, 0.33, 0.94, 0.48, 0.75],
       [0.9 , 0.43, 0.42, 0.86, 0.28, 0.26, 0.53, 0.01, 0.29, 0.53],
       [0.41, 0.22, 0.96, 0.12, 0.42, 0.82, 0.99, 0.74, 0.65, 0.58],
       [0.58, 0.19, 0.01, 0.62, 0.44, 0.72, 0.56, 0.12, 0.27, 0.83]])

#### 81. 统计随机数组中的各元素的数量

In [92]:
Z = np.random.randint(0,100,25).reshape(5,5)
print(Z)

np.unique(Z, return_counts=True) # 返回值中，第 2 个数组对应第 1 个数组元素的数量

[[ 0 42  3 23  2]
 [83 91 84 70 70]
 [19 42 23  8 32]
 [61 53 11 22 32]
 [20 13 69  9 27]]


(array([ 0,  2,  3,  8,  9, 11, 13, 19, 20, 22, 23, 27, 32, 42, 53, 61, 69,
        70, 83, 84, 91]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1]))

#### 82. 将数组中各元素按指定分类转换为文本值

In [93]:
# 指定类别如下
# 1 → 汽车
# 2 → 公交车
# 3 → 火车


Z = np.random.randint(1,4,10)
print(Z)

label_map = {1: "汽车", 2: "公交车", 3: "火车"}

[label_map[x] for x in Z]

[2 3 1 2 3 1 1 1 2 1]


['\xe5\x85\xac\xe4\xba\xa4\xe8\xbd\xa6',
 '\xe7\x81\xab\xe8\xbd\xa6',
 '\xe6\xb1\xbd\xe8\xbd\xa6',
 '\xe5\x85\xac\xe4\xba\xa4\xe8\xbd\xa6',
 '\xe7\x81\xab\xe8\xbd\xa6',
 '\xe6\xb1\xbd\xe8\xbd\xa6',
 '\xe6\xb1\xbd\xe8\xbd\xa6',
 '\xe6\xb1\xbd\xe8\xbd\xa6',
 '\xe5\x85\xac\xe4\xba\xa4\xe8\xbd\xa6',
 '\xe6\xb1\xbd\xe8\xbd\xa6']

#### 83. 将多个 1 维数组拼合为单个 Ndarray

In [94]:
Z1 = np.arange(3)
Z2 = np.arange(3,7)
Z3 = np.arange(7,10)

Z = np.array([Z1, Z2, Z3])
print(Z)

np.concatenate(Z)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 84. 打印各元素在数组中升序排列的索引

In [95]:
a = np.random.randint(100, size=10)
print('Array: ', a)

a.argsort().argsort()

('Array: ', array([54,  4, 60, 74, 11, 76, 59, 46,  5, 76]))


array([4, 0, 6, 7, 2, 8, 5, 3, 1, 9])

#### 85. 得到二维随机数组各行的最大值

In [96]:
Z = np.random.randint(1,100, [5,5])
print(Z)

np.amax(Z, axis=1)

[[28 73 19 87 13]
 [35 25  7 68 61]
 [69 81  4 17 97]
 [42 33 72 78 86]
 [55 28 90 52 61]]


array([87, 68, 97, 86, 90])

#### 86. 得到二维随机数组各行的最小值（区别上面的方法）

In [97]:
Z = np.random.randint(1,100, [5,5])
print(Z)

np.apply_along_axis(np.min, arr=Z, axis=1)

[[37 61 47 49 16]
 [62 39 62 61 21]
 [83 77 84 68 47]
 [75 62 48 78 11]
 [97  4 12 60 79]]


array([16, 21, 47, 11,  4])

#### 87. 计算两个数组之间的欧氏距离

In [98]:
a = np.array([1, 2])
b = np.array([7, 8])

# 数学计算方法
print(np.sqrt(np.power((8-2), 2) + np.power((7-1), 2)))

# NumPy 计算
np.linalg.norm(b-a)

8.48528137423857


8.48528137423857

#### 88. 打印复数的实部和虚部

In [99]:
a = np.array([1 + 2j, 3 + 4j, 5 + 6j])

print("实部：", a.real)
print("虚部：", a.imag)

('\xe5\xae\x9e\xe9\x83\xa8\xef\xbc\x9a', array([1., 3., 5.]))
('\xe8\x99\x9a\xe9\x83\xa8\xef\xbc\x9a', array([2., 4., 6.]))


#### 89. 求解给出矩阵的逆矩阵并验证

In [100]:
matrix = np.array([[1., 2.], [3., 4.]])

inverse_matrix = np.linalg.inv(matrix)

# 验证原矩阵和逆矩阵的点积是否为单位矩阵
assert np.allclose(np.dot(matrix, inverse_matrix), np.eye(2))

inverse_matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### 90. 使用 Z-Score 标准化算法对数据进行标准化处理

Z-Score 标准化公式：
$$Z = \frac{X-\mathrm{mean}(X)}{\mathrm{sd}(X)}$$

In [101]:
# 根据公式定义函数
def zscore(x, axis = None):
    xmean = x.mean(axis=axis, keepdims=True)
    xstd  = np.std(x, axis=axis, keepdims=True)
    zscore = (x-xmean)/xstd
    return zscore

# 生成随机数据
Z = np.random.randint(10, size=(5,5))
print(Z)

zscore(Z)

[[2 4 3 9 1]
 [3 7 1 7 0]
 [4 2 0 7 6]
 [3 1 1 6 5]
 [8 2 9 5 4]]


array([[-0.73,  0.  , -0.37,  1.83, -1.1 ],
       [-0.37,  1.1 , -1.1 ,  1.1 , -1.47],
       [ 0.  , -0.73, -1.47,  1.1 ,  0.73],
       [-0.37, -1.1 , -1.1 ,  0.73,  0.37],
       [ 1.47, -0.73,  1.83,  0.37,  0.  ]])

#### 91. 使用 Min-Max 标准化算法对数据进行标准化处理

Min-Max 标准化公式：
$$Y = \frac{Z-\min(Z)}{\max(Z)-\min(Z)}$$

In [102]:
# 根据公式定义函数
def min_max(x, axis=None):
    min = x.min(axis=axis, keepdims=True)
    max = x.max(axis=axis, keepdims=True)
    result = (x-min)/(max-min)
    return result

# 生成随机数据
Z = np.random.randint(10, size=(5,5))
print(Z)

min_max(Z)

[[1 3 2 6 8]
 [4 1 4 8 3]
 [0 3 3 9 1]
 [4 1 8 3 1]
 [9 0 8 5 0]]


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

#### 92. 使用 L2 范数对数据进行标准化处理

L2 范数计算公式：
$$L_2 = \sqrt{x_1^2 + x_2^2 + \ldots + x_i^2}$$

In [103]:
# 根据公式定义函数
def l2_normalize(v, axis=-1, order=2):
    l2 = np.linalg.norm(v, ord = order, axis=axis, keepdims=True)
    l2[l2==0] = 1
    return v/l2

# 生成随机数据
Z = np.random.randint(10, size=(5,5))
print(Z)

l2_normalize(Z)

[[7 0 4 9 7]
 [7 8 6 4 1]
 [4 2 3 2 1]
 [3 1 5 8 7]
 [3 4 4 4 1]]


array([[0.5 , 0.  , 0.29, 0.64, 0.5 ],
       [0.54, 0.62, 0.47, 0.31, 0.08],
       [0.69, 0.34, 0.51, 0.34, 0.17],
       [0.25, 0.08, 0.41, 0.66, 0.58],
       [0.39, 0.53, 0.53, 0.53, 0.13]])

#### 93. 使用 NumPy 计算变量直接的相关性系数

In [104]:
Z = np.array([
    [1, 2, 1, 9, 10, 3, 2, 6, 7], # 特征 A
    [2, 1, 8, 3, 7, 5, 10, 7, 2], # 特征 B
    [2, 1, 1, 8, 9, 4, 3, 5, 7]]) # 特征 C

np.corrcoef(Z)

array([[ 1.  , -0.06,  0.97],
       [-0.06,  1.  , -0.01],
       [ 0.97, -0.01,  1.  ]])

相关性系数取值从 `0-1` 变换，靠近 1 则代表相关性较强。结果如下所示，变量 A 与变量 A 直接的相关性系数为 `1`，因为是同一个变量；变量 A 与 变量 B 之间的相关性系数为 `-0.06`，说明几乎不相关。变量 A 与变量 C 之间的相关性系数为 `0.97`，说明相关性较强。
```
         [A]     [B]     [C]
array([[ 1.  , -0.06,  0.97]   [A]
       [-0.06,  1.  , -0.01],  [B]
       [ 0.97, -0.01,  1.  ]]) [C]
```

#### 94. 使用 NumPy 计算矩阵的特征值和特征向量

In [105]:
M = np.matrix([[1,2,3], [4,5,6], [7,8,9]])

w, v = np.linalg.eig(M)

# w 对应特征值，v 对应特征向量
w, v

(array([ 1.61e+01, -1.12e+00, -1.30e-15]), matrix([[-0.23, -0.79,  0.41],
         [-0.53, -0.09, -0.82],
         [-0.82,  0.61,  0.41]]))

我们可以通过 `P'AP=M` 公式反算，验证是否能得到原矩阵。

In [106]:
v * np.diag(w) * np.linalg.inv(v)

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

#### 95. 使用 NumPy 计算 Ndarray 两相邻元素差值

In [107]:
Z = np.random.randint(1,10,10)
print(Z)

# 计算 Z 两相邻元素差值
print(np.diff(Z, n=1))

# 重复计算 2 次
print(np.diff(Z, n=2))

# 重复计算 3 次
print(np.diff(Z, n=3))

[3 8 2 7 1 8 1 5 2 2]
[ 5 -6  5 -6  7 -7  4 -3  0]
[-11  11 -11  13 -14  11  -7   3]
[ 22 -22  24 -27  25 -18  10]


#### 96. 使用 NumPy 将 Ndarray 相邻元素依次累加

In [108]:
Z = np.random.randint(1,10,10)
print(Z)

"""
[第一个元素, 第一个元素 + 第二个元素, 第一个元素 + 第二个元素 + 第三个元素, ...]
"""
np.cumsum(Z)

[8 2 3 5 2 8 3 6 7 6]


array([ 8, 10, 13, 18, 20, 28, 31, 37, 44, 50])

#### 97. 使用 NumPy 按列连接两个数组（要求列数一致）

In [109]:
M1 = np.array([1, 2, 3])
M2 = np.array([4, 5, 6])

np.c_[M1, M2]

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 98. 使用 NumPy 按行连接两个数组（要求行数一致）

In [110]:
M1 = np.array([1, 2, 3])
M2 = np.array([4, 5, 6])

np.r_[M1, M2]

array([1, 2, 3, 4, 5, 6])

#### 99. 使用 NumPy 打印九九乘法表

In [111]:
np.fromfunction(lambda i, j: (i + 1) * (j + 1), (9, 9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

#### 100. 使用 Numpy 将实验楼 LOGO 转换为 Ndarray 数组

In [ ]:
from io import BytesIO
# Pillow
from PIL import Image
import PIL, requests

# 通过链接下载图像
URL = 'https://static.shiyanlou.com/img/logo-black.png'
response = requests.get(URL)

# 将内容读取为图像
I = Image.open(BytesIO(response.content))

# 将图像转换为 Ndarray
shiyanlou = np.asarray(I)
shiyanlou

In [ ]:
# 将转换后的 Ndarray 重新绘制成图像
from matplotlib import pyplot as plt
%matplotlib inline

plt.imshow(shiyanlou)
plt.show()

## <a id = "3">3. 实验总结</a>

如果你亲自动手做完了上面的 100 道练习题，相信你已经对 Numpy 模块的熟练程度又提升了不少。我们推荐你定期回顾这些题目，相信你一定会熟能生巧。本次实验涉及的知识点主要有：
- 创建数组
- 数组运算
- 数学函数
- 数组切片和索引
- 数组形状操作
- 数组排序
- 数组统计